# basic travis config to build with gcc/clang plus 32-/64-bit

language: c
python:
  - "2.4"
git:
  submodules: false
env:
  global:
    - PKGS_32="gcc-multilib g++-multilib libc6-dev-i386 libglu1-mesa-dev:i386 libxext-dev:i386 libsdl1.2-dev:i386 libsdl-image1.2-dev:i386"
    - PKGS_64="libsdl1.2-dev libsdl-image1.2-dev"
#- PLAT_PKGS="gcc-multilib g++-multilib libc6-dev-i386"
#- CORE_PKGS="libusb-1.0-0-dev libiscsi-dev librados-dev libncurses5-dev"
#- NET_PKGS="libseccomp-dev libgnutls-dev libssh2-1-dev  libspice-server-dev libspice-protocol-dev libnss3-dev"
#- GUI_PKGS="libgtk-3-dev libvte-2.90-dev libsdl1.2-dev libpng12-dev libpixman-1-dev libsdl-image1.2-dev"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ${PKGS}
before_script:
  - ./configure --target-list=gnuarmeclipse-softmmu
script:
  - make -j2
matrix:
  include:
    # 32-bit GCC
    - env:
      - PKGS=${PKGS_32}
      - CFLAGS=-m32
      - CXXFLAGS=-m32
      - LDFLAGS=-m32
      compiler: gcc
    # 64-bit GCC
    - env:
      - PKGS=${PKGS_64}
      - CFLAGS=-m64
      - CXXFLAGS=-m64
      - LDFLAGS=-m64
      compiler: gcc
  ignore:
    # 32-bit clang
    - env:
      - CFLAGS=-m32
      - CXXFLAGS=-m32
      - LDFLAGS=-m32
      compiler: clang
    # 64-bit clang
    - env:
      - CFLAGS=-m64
      - CXXFLAGS=-m64
      - LDFLAGS=-m64
      compiler: clang
